package beans;
// Generated Dec 21, 2020 11:16:42 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ItemStock generated by hbm2java
 */
public class ItemStock implements java.io.Serializable {

    private Integer iditemStock;
    private Category category;
    private String productCode;
    private String itemStockName;
    private String itemDescription;
    private BigDecimal itemPrice;
    private BigDecimal sellingPrice;
    private BigDecimal discount;
    private boolean availability;
    private String imageItem;
    private boolean delivery;
    private String deliveryTimePeriod;
    private boolean warranty;
    private String warrantyPeriod;
    private Date dateCreated;
    private Date lastUpdated;

    public ItemStock() {
    }

    public ItemStock(Category category, String productCode, String itemStockName, String itemDescription, BigDecimal itemPrice, BigDecimal sellingPrice, BigDecimal discount, boolean availability, String imageItem, boolean delivery, String deliveryTimePeriod, boolean warranty, String warrantyPeriod, Date dateCreated, Date lastUpdated) {
        this.category = category;
        this.productCode = productCode;
        this.itemStockName = itemStockName;
        this.itemDescription = itemDescription;
        this.itemPrice = itemPrice;
        this.sellingPrice = sellingPrice;
        this.discount = discount;
        this.availability = availability;
        this.imageItem = imageItem;
        this.delivery = delivery;
        this.deliveryTimePeriod = deliveryTimePeriod;
        this.warranty = warranty;
        this.warrantyPeriod = warrantyPeriod;
        this.dateCreated = dateCreated;
        this.lastUpdated = lastUpdated;
    }

    public Integer getIditemStock() {
        return this.iditemStock;
    }

    public void setIditemStock(Integer iditemStock) {
        this.iditemStock = iditemStock;
    }

    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public String getProductCode() {
        return this.productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getItemStockName() {
        return this.itemStockName;
    }

    public void setItemStockName(String itemStockName) {
        this.itemStockName = itemStockName;
    }

    public String getItemDescription() {
        return this.itemDescription;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    public BigDecimal getItemPrice() {
        return this.itemPrice;
    }

    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    public BigDecimal getSellingPrice() {
        return this.sellingPrice;
    }

    public void setSellingPrice(BigDecimal sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    public BigDecimal getDiscount() {
        return this.discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    public boolean getAvailability() {
        return this.availability;
    }

    public void setAvailability(boolean availability) {
        this.availability = availability;
    }

    public String getImageItem() {
        return this.imageItem;
    }

    public void setImageItem(String imageItem) {
        this.imageItem = imageItem;
    }

    public boolean getDelivery() {
        return this.delivery;
    }

    public void setDelivery(boolean delivery) {
        this.delivery = delivery;
    }

    public String getDeliveryTimePeriod() {
        return this.deliveryTimePeriod;
    }

    public void setDeliveryTimePeriod(String deliveryTimePeriod) {
        this.deliveryTimePeriod = deliveryTimePeriod;
    }

    public boolean getWarranty() {
        return this.warranty;
    }

    public void setWarranty(boolean warranty) {
        this.warranty = warranty;
    }

    public String getWarrantyPeriod() {
        return this.warrantyPeriod;
    }

    public void setWarrantyPeriod(String warrantyPeriod) {
        this.warrantyPeriod = warrantyPeriod;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

}
